# Site settings
title: Walkthroughs
email: leochilds@mounterebus.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Who needs a description?
baseurl: "/learnyounode-walkthrough" # the subpath of your site, e.g. /blog/
url: "http://leochilds.github.io" # the base hostname & protocol for your site
twitter_username: childsleo
github_username:  leochilds

# Build settings
markdown: kramdown
